### ISSUE TITLE
Board erroring out due to playoffs

### ISSUE THREAD

**Issue by Coop21** [riffnshred/nhl-led-scoreboard#280] opened 2021-05-13 23:28 UTC
**Describe the bug**
Board is not starting up as of today.  Note: I changed my default from a non-playoff team (Kings) to a playoff team (Blues) and the board would still not work.  See screen shot of error below.  

**Logs**
![image0](https://user-images.githubusercontent.com/80079281/118199406-a8415200-b418-11eb-980c-34c9fa1ee076.jpg)

**Comment by pjockey** [comment] 2021-05-14 01:06
what does your config.json look like? Can you post?

**Comment by riffnshred** [comment] 2021-05-14 01:16
This is an issue caused by some playoff data missing in the API. I got a fix for it, but other issues came out with it and I need to wait and see how the playoff data will settle till this weekend before I do an official release. I will have it in the Beta branch soon tho.

**Comment by riffnshred** [comment] 2021-05-14 01:40
Fix is on the Beta

**Comment by justinaramian** [comment] 2021-05-14 14:47
I woke up this morning to find my board was now working again. Didn't make any changes. Just let it sit in a boot loop over night.

**Comment by riffnshred** [comment] 2021-05-20 12:36
All seems normal now. closing.

cheers

**Closed by riffnshred** 2021-05-20 12:36 UTC
